server:
  port: 8081

spring:
  application:
    name: cloud-user
  datasource:
    url: jdbc:mysql://localhost:3306/test?useSSL=false&useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  security:
    user:
      name: user
      password: 123456
  mail:
    default-encoding: UTF-8
    protocol: smtps
    host: smtp.qq.com
    username: abc@qq.com
    password: xxxyyy
    properties:
      mail:
        smtp:
          from: MyCloud-NoReply <abc@qq.com>

mybatis:
  mapper-locations: classpath*:mapper/*.xml

mycloud:
  common:
    controller:
      globalResponseWrapping: true
