server:
  port: 8081

spring:
  application:
    name: cloud-user
  datasource:
    url: jdbc:mysql://localhost:3306/test?useSSL=false&useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  security:
    user:
      name: user
      password: 123456
  # redis 哨兵集群
  data:
    redis:
      sentinel:
        master: mymaster
        nodes: archlinux:26379,archlinux:26380,archlinux:26381
      password: root
  # kafka 集群
  kafka:
    bootstrap-servers: archlinux:9192
    # 自定义的属性和参数，用于指定topic名称
    custom:
      init:
        topic: validCodeEmailMessages
    producer:
      retries: 5
      batch-size: 16384
      acks: -1
      buffer-memory: 67108864
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.looko.mycloud.user.serialization.KafkaSimpleMailMessageSerializer
    consumer:
      group-id: userGroup
      bootstrap-servers: archlinux:9192
      # 处理毒丸现象 (poison pill)
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.json.trusted.packages: "org.springframework.mail"
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: org.looko.mycloud.user.serialization.KafkaSimpleMailMessageDeserializer
  mail:
    default-encoding: UTF-8
    protocol: smtps
    host: smtp.qq.com
    username: abc@qq.com
    password: xxxyyy
    properties:
      mail:
        smtp:
          from: MyCloud-NoReply <abc@qq.com>

mybatis:
  mapper-locations: classpath*:mapper/*.xml

mycloud:
  common:
    controller:
      globalResponseWrapping: true
