server:
  port: 8100
spring:
  profiles:
    include:
      - routes
  application:
    name: cloud-gateway
  cloud:
    nacos:
      discovery:
        server-addr: archlinux:8848
        username: nacos
        password: nacos

    gateway:
      discovery:
        locator:
          # 开启从注册中心动态创建路由的功能，利用微服务名进行路由
          enabled: true
          # 用小写的请求路径的服务名匹配服务。默认为false（大写）。（因为服务注册时服务名被转成大写）
          lowerCaseServiceId: true
      default-filters:
        # 响应头去重
        - DedupeResponseHeader=Access-Control-Allow-Origin, RETAIN_UNIQUE
      # 跨域配置
#      globalcors:
#        cors-configurations:
#          '[/**]':
#            allowedOrigins:
#              - http://localhost:5173
#              - http://archlinux:5173
#            allowedMethods:
#              - GET
#              - POST
#            allowedHeaders: "*"
#            allowCredentials: true

mycloud:
  gateway:
    jwt:
      secret: '!7Rt-fjyBkQnamW78ekRpC'
      # 默认有效期 8 小时 1000L * 60 * 60 * 8 = 28800000
      expire: 28800000